# Generated by Django 4.2 on 2026-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_in_time', models.DateTimeField(blank=True, null=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('sign_in_selfie', models.ImageField(blank=True, null=True, upload_to='selfies/')),
                ('sign_out_selfie', models.ImageField(blank=True, null=True, upload_to='selfies/')),
                ('sign_in_lat', models.FloatField(blank=True, null=True)),
                ('sign_in_lon', models.FloatField(blank=True, null=True)),
                ('sign_out_lat', models.FloatField(blank=True, null=True)),
                ('sign_out_lon', models.FloatField(blank=True, null=True)),
                ('sign_in_verified', models.BooleanField(default=False)),
                ('sign_out_verified', models.BooleanField(default=False)),
                ('location_suspicious', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('safety', 'Safety'), ('resource', 'Resource Shortage'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
