# Generated by Django 4.2 on 2026-05-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_service', '0001_initial'),
        ('school_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_service.school'),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_service.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_service.school'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_service.attendancesession'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_service.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('school', 'date')},
        ),
    ]
