# Generated by Django 4.2 on 2026-05-01 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=255)),
                ('village', models.CharField(default='', max_length=100)),
                ('taluka', models.CharField(default='Shirpur', max_length=100)),
                ('district', models.CharField(default='Dhule', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField(default=100.0)),
                ('logo', models.CharField(default='/placeholders/school_logo.png', max_length=255)),
                ('student_count', models.IntegerField(default=0)),
                ('established_year', models.IntegerField(default=2000)),
                ('map_link', models.URLField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.CharField(default='/placeholders/teacher.png', max_length=255)),
                ('standard', models.IntegerField(choices=[(1, 'Standard 1'), (2, 'Standard 2'), (3, 'Standard 3'), (4, 'Standard 4')])),
                ('division', models.CharField(default='A', max_length=5)),
                ('salary_block_recommended', models.BooleanField(default=False)),
                ('salary_held', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(choices=[(1, 'Standard 1'), (2, 'Standard 2'), (3, 'Standard 3'), (4, 'Standard 4')])),
                ('division', models.CharField(default='A', max_length=5)),
                ('student_count', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='school_service.school')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_divisions', to='school_service.teacher')),
            ],
            options={
                'unique_together': {('school', 'standard', 'division')},
            },
        ),
    ]
